version: '3.8'

services:
  database:
    container_name: comment_tree_db
    image: mysql:8.0.33
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: comment_tree
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - mysql:/var/lib/mysql
  php:
    container_name: comment_tree_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/comment_tree
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/comment_tree
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php
volumes:
  mysql:
